AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloTwitchViewers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        HelloTwitchAPI:
          Type: Api
          Properties:
            Path: /hello-twitch
            Method: GET

  

  